name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-app
        with:
          setup-ruby: "true"

      - name: Run linting
        run: ./bin/standardrb --no-fix

  test-import:
    runs-on: ubuntu-latest
    services:
        search:
          image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
          ports:
            - "9200:9200"
          env:
            "discovery.type": "single-node"
          options: >-
            --health-cmd "curl --silent --fail http://localhost:9200/_cluster/health || exit 1"

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-app
        with:
          setup-ruby: "true"

      - name: Test Importing Ruby Documentation
        run: ./bin/rake "import:ruby[3.1.2]"

  test:
    runs-on: ubuntu-latest
    services:
      search:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
        ports:
          - "9200:9200"
        env:
          "discovery.type": "single-node"
        options: >-
          --health-cmd "curl --silent --fail http://localhost:9200/_cluster/health || exit 1"

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-app
        with:
          setup-ruby: "true"

      - name: Test Zeitwerk
        run: ./bin/rails zeitwerk:check

      - name: Run Tests
        env:
          ELASTICSEARCH_URL: "http://localhost:9200"
        run: |
          npm run build && npm run build:css
          ./bin/rails test
